const REQUIRED_SECTIONS=[{id:'Local',icon:'🏘️'},{id:'National',icon:'🇺🇸'},{id:'Politics',icon:'🏛️'},{id:'Crime',icon:'🚓'},{id:'Traffic',icon:'🚗'},{id:'Sports',icon:'🏈'},{id:'Culture',icon:'🎭'}];
const STORAGE={sections:'bc.sections',streak:'bc.streak',lastOpen:'bc.lastOpen',minutes:'bc.minutes'};
let FEED={dailyGoalMinutes:10,stories:[]};let state={index:0,autoplay:true,timer:null};
const $=s=>document.querySelector(s);
const todayKey=()=>new Date().toISOString().slice(0,10);
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1200);}
function renderPunchcard(){const wrap=document.getElementById('punchcard');wrap.innerHTML='';const done=(JSON.parse(localStorage.getItem(STORAGE.sections)||'{}')[todayKey()]||{});REQUIRED_SECTIONS.forEach(s=>{const d=document.createElement('div');d.className='punch-slot'+(done[s.id]?' filled':'');d.textContent=s.icon+' '+s.id;wrap.appendChild(d);});}
function markSection(sec){const map=JSON.parse(localStorage.getItem(STORAGE.sections)||'{}');const k=todayKey();map[k]=map[k]||{};map[k][sec]=true;localStorage.setItem(STORAGE.sections,JSON.stringify(map));renderPunchcard();}
function ringPercent(mins,goal){const C=2*Math.PI*52;const pct=Math.max(0,Math.min(1,mins/Math.max(1,goal)));document.getElementById('ringFg').setAttribute('stroke-dasharray',`${pct*C} ${C}`);}
function minutesToday(){const map=JSON.parse(localStorage.getItem(STORAGE.minutes)||'{}');return map[todayKey()]||0}
function addMinutes(n){const map=JSON.parse(localStorage.getItem(STORAGE.minutes)||'{}');const k=todayKey();map[k]=(map[k]||0)+n;localStorage.setItem(STORAGE.minutes',JSON.stringify(map));document.getElementById('minutesToday').textContent=map[k];ringPercent(map[k],10);}
function bumpStreak(){const last=localStorage.getItem(STORAGE.lastOpen);const today=todayKey();let s=parseInt(localStorage.getItem(STORAGE.streak)||'0',10)||0;if(last!==today){const y=new Date();y.setDate(y.getDate()-1);s=(last===y.toISOString().slice(0,10))?s+1:1;localStorage.setItem(STORAGE.lastOpen,today);localStorage.setItem(STORAGE.streak,String(s));}document.getElementById('streakCount').textContent=s;}
function renderList(){const list=document.getElementById('storyList');list.innerHTML='';FEED.stories.forEach((s,i)=>{const a=document.createElement('a');a.href='#';a.className='story-item'+(i===state.index?' active':'');a.innerHTML=`<div class="title">${s.title}</div><div class="meta">${s.section} • ${Math.round((s.durationSec||75)/60)} min</div>`;a.onclick=e=>{e.preventDefault();open(i,true)};list.appendChild(a);});}
function open(i,stop=false){state.index=Math.max(0,Math.min(FEED.stories.length-1,i));const s=FEED.stories[state.index];document.getElementById('storyTitle').textContent=s.title;document.getElementById('storyUrl').href=s.url;document.getElementById('storyTopic').textContent=s.section;document.getElementById('storyDuration').textContent=Math.max(1,Math.round((s.durationSec||75)/60));document.getElementById('storySummary').textContent=s.summary;renderList();if(stop&&state.timer){clearInterval(state.timer)}startTimer(s);}
function startTimer(s){if(state.timer){clearInterval(state.timer)}let t=s.durationSec||75;state.timer=setInterval(()=>{t--;if(t<=0){clearInterval(state.timer);state.timer=null;complete(s);if(state.autoplay)open(state.index+1);}},1000);}
function complete(s){markSection(s.section||'News');toast('✓ Completed');}
async function load(){const res=await fetch('/api/brief?limit=14');FEED=await res.json();document.getElementById('goal').textContent=FEED.dailyGoalMinutes||10;renderList();open(0);}
document.addEventListener('DOMContentLoaded',()=>{bumpStreak();document.getElementById('minutesToday').textContent=minutesToday();ringPercent(minutesToday(),10);renderPunchcard();document.getElementById('btnNext').onclick=()=>open(state.index+1);document.getElementById('btnPrev').onclick=()=>open(state.index-1,true);document.getElementById('btnComplete').onclick=()=>complete(FEED.stories[state.index]);load();});
